/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author bonnychen
 */
public class UnlockNewAnimalView extends javax.swing.JPanel {

    /**
     * Creates new form UnlockNewAnimalView
     */
    public UnlockNewAnimalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newAnimePanel = new javax.swing.JPanel();
        newAnimalHolderPanel = new javax.swing.JPanel();
        animal = new javax.swing.JLabel();
        animalLabel = new javax.swing.JLabel();
        funFactLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setLayout(null);

        newAnimePanel.setBackground(new java.awt.Color(255, 204, 102));

        newAnimalHolderPanel.setBackground(new java.awt.Color(255, 238, 173));

        animal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/alpaca.png"))); // NOI18N

        animalLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        animalLabel.setText("Animal Name");

        funFactLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        funFactLabel.setText("Fun Fact: ");

        javax.swing.GroupLayout newAnimalHolderPanelLayout = new javax.swing.GroupLayout(newAnimalHolderPanel);
        newAnimalHolderPanel.setLayout(newAnimalHolderPanelLayout);
        newAnimalHolderPanelLayout.setHorizontalGroup(
            newAnimalHolderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newAnimalHolderPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(animal)
                .addGap(18, 18, 18)
                .addGroup(newAnimalHolderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(funFactLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(animalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        newAnimalHolderPanelLayout.setVerticalGroup(
            newAnimalHolderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newAnimalHolderPanelLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(animal)
                .addGap(31, 31, 31))
            .addGroup(newAnimalHolderPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(animalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(funFactLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        titleLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        titleLabel.setText("You unlocked a new animal! ");

        nextButton.setBackground(new java.awt.Color(255, 238, 173));
        nextButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        nextButton.setText("Nice");

        javax.swing.GroupLayout newAnimePanelLayout = new javax.swing.GroupLayout(newAnimePanel);
        newAnimePanel.setLayout(newAnimePanelLayout);
        newAnimePanelLayout.setHorizontalGroup(
            newAnimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newAnimePanelLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(titleLabel)
                .addGap(32, 32, 32))
            .addGroup(newAnimePanelLayout.createSequentialGroup()
                .addGroup(newAnimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newAnimePanelLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newAnimePanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(newAnimalHolderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        newAnimePanelLayout.setVerticalGroup(
            newAnimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newAnimePanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(titleLabel)
                .addGap(36, 36, 36)
                .addComponent(newAnimalHolderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        add(newAnimePanel);
        newAnimePanel.setBounds(260, 110, 400, 340);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farm.png"))); // NOI18N
        add(background);
        background.setBounds(0, 0, 927, 570);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel animal;
    private javax.swing.JLabel animalLabel;
    private javax.swing.JLabel background;
    private javax.swing.JLabel funFactLabel;
    private javax.swing.JPanel newAnimalHolderPanel;
    private javax.swing.JPanel newAnimePanel;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
